name: CI

on:
  workflow_dispatch:
    branches: [ dev ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login in dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Not sure what this one does
      uses: docker/setup-buildx-action@v1

    - name: Build and push image to dockerhub
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: voorloop/decouphage:latest
